# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMDemoSB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '5.1.0'
  pod 'RxCocoa', '5.1.0'

  target 'MVVMDemoSBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMDemoSBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
